### ISSUE TITLE
 exception in forkbuntu

### ISSUE THREAD

**Issue by shalomd73** [jamrizzi/forkbuntu#1]
Hi,
I tried to use forkbuntu, I did 
pip3 install forkbuntu
forkbuntu
 
I took for example the config.yml

name: 
    Forkbuntu
        version: 18.04
        paths:
            iso: ubuntu-18.04-server-amd64.iso
           output: forkbuntu.iso
        packages:
            - cowsay
       apt:
         restricted: false
         multiarch: false

And it got the following exception: 
root@isoMaker18:/# forkbuntu
Traceback (most recent call last):
  File "/usr/local/bin/forkbuntu", line 7, in <module>
    from forkbuntu.__main__ import main
  File "/usr/local/lib/python3.6/dist-packages/forkbuntu/__init__.py", line 90, in <module>
    'tmp': mkdtemp()
  File "/usr/local/lib/python3.6/dist-packages/forkbuntu/__init__.py", line 57, in load_conf
    _.map(conf.paths, lambda x: path.abspath(path.join(conf.paths.cwd, x)))
  File "/usr/local/lib/python3.6/dist-packages/pydash/collections.py", line 538, in map_
    return list(itermap(collection, iteratee))
  File "/usr/local/lib/python3.6/dist-packages/pydash/collections.py", line 1102, in itermap
    for result in iteriteratee(collection, iteratee):
  File "/usr/local/lib/python3.6/dist-packages/pydash/helpers.py", line 93, in iteriteratee
    yield (callit(cbk, item, key, obj, argcount=argcount),
  File "/usr/local/lib/python3.6/dist-packages/pydash/helpers.py", line 37, in callit
    return iteratee(*args[:argstop])
  File "/usr/local/lib/python3.6/dist-packages/forkbuntu/__init__.py", line 57, in <lambda>
    _.map(conf.paths, lambda x: path.abspath(path.join(conf.paths.cwd, x)))
  File "/usr/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.6/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'list'
Regards,
Shalom David

**Comment by clayrisser** [comment]
Sorry for the delay. I'll take a look at it this week.
